require conf/distro/poky.conf

DISTRO = "rz-bsp"
DISTROOVERRIDES = "poky:rz-bsp"

# Override these in poky based distros
DISTRO_FEATURES:append = " pam can"
DISTRO_FEATURES:remove = " x11"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += "kernel-image kernel-devicetree"

PREFERRED_VERSION_u-boot ?= "2023.10%"
PREFERRED_PROVIDER_virtual/kernel ?= "linux-renesas"
PREFERRED_VERSION_linux-renesas ?= "6.1%"
PREFERRED_VERSION_linux-libc-headers ?= "6.1%"

SANITY_TESTED_DISTROS ?= " \
	ubuntu-22.04 \n \
	"

# Using Systemd as Initialization Manager
INIT_MANAGER = "systemd"

# Using systemd-journald without a traditional syslog daemon
VIRTUAL-RUNTIME_syslog = ""
VIRTUAL-RUNTIME_base-utils-syslog = ""
