#!/bin/sh
#
### BEGIN INIT INFO
# Provides: mm
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 5
# Default-Stop:      0 1 6
### END INIT INFO

case "$1" in
"start")
	# insert kernel modules
        /sbin/modprobe -q -a 8723bu
	;;
stop)
	# remove kernel modules
        /sbin/modprobe -q -r -a 8723bu
	;;
reload|restart)
	$0 stop
        sleep 1
        $0 start
	;;
*)
	echo "usage: $0 { start | stop | restart }"
	;;
esac
