# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rzt2h"
BBFILE_PATTERN_rzt2h = "^${LAYERDIR}/"
BBFILE_PRIORITY_rzt2h = "15"

LAYERDEPENDS_rzt2h = "rz-common"
LAYERSERIES_COMPAT_rzt2h = "dunfell"
