#@TYPE: Machine
#@NAME: hihope-rzg2n machine
#@DESCRIPTION: Hoperun Technology HiHope RZ/G2N platform (hihope-rzg2n)

require conf/machine/include/arm/armv8a/tune-cortexa57.inc
require conf/machine/include/rz-common.inc
require conf/machine/include/rzg2h-family.inc

# Machine configuration
MACHINE_FEATURES:append = " alsa ext2 pci serial usbgadget usbhost can"

SERIAL_CONSOLES ?= "115200;ttySC0"

# Supported devicetree
KERNEL_DEVICETREE ?= " \
	renesas/r8a774b1-hihope-rzg2n.dtb \
	renesas/r8a774b1-hihope-rzg2n-ex.dtb \
	renesas/r8a774b1-hihope-rzg2n-ex-idk-1110wr.dtb \
	renesas/r8a774b1-hihope-rzg2n-ex-mipi-2.1.dtb \
	renesas/r8a774b1-hihope-rzg2n-ex-mipi-2.4.dtb \
"

IMAGE_FSTYPES:remove = "wic.gz wic.bmap"
