#@TYPE: Machine
#@NAME: hihope-rzg2h
#@DESCRIPTION: Reference machine configuration for the Hoperun Technology HiHope RZ/G2H platform (hihope-rzg2h)

require conf/machine/include/arm/armv8a/tune-cortexa57-cortexa53.inc
require conf/machine/include/rz-common.inc
require conf/machine/include/rzg2h-family.inc

# Machine configuration
MACHINE_FEATURES:append = " alsa ext2 pci serial usbgadget usbhost can"

SERIAL_CONSOLES ?= "115200;ttySC0"

# Trusted Firmware-A configuration
PREFERRED_VERSION_trusted-firmware-a ?= "2.9%"
TFA_PLATFORM ?= "rzg"
TFA_BUILD_TARGET ?= "bl2 bl31"

# U-Boot Configuration
UBOOT_CONFIG ??= "hihope-rzg2h"
UBOOT_CONFIG[hihope-rzg2h] = "hihope_rzg2_defconfig"
PREFERRED_VERSION_u-boot = "2021.10%"

# flash writer
EXTRA_IMAGEDEPENDS += " flash-writer"

# Supported devicetree
KERNEL_DEVICETREE ?= " \
	renesas/r8a774e1-hihope-rzg2h.dtb \
	renesas/r8a774e1-hihope-rzg2h-ex.dtb \
	renesas/r8a774e1-hihope-rzg2h-ex-idk-1110wr.dtb \
	renesas/r8a774e1-hihope-rzg2h-ex-mipi-2.1.dtb \
	renesas/r8a774e1-hihope-rzg2h-ex-mipi-2.4.dtb \
"

IMAGE_FSTYPES:remove = "wic.gz wic.bmap"
