#@TYPE: Machine
#@NAME: rzv2h-evk-version1/2 machine
#@DESCRIPTION: RZ/V2H Evaluation Board Kit

require conf/machine/include/rzv2h-family.inc
require conf/machine/include/arm/armv8-2a/tune-cortexa55.inc
require conf/machine/include/rz-common.inc

SERIAL_CONSOLES ?= "115200;ttySC0"
PREFERRED_VERSION_trusted-firmware-a ?= "2.10%"
TFA_PLATFORM ?= "v2h"
TFA_BOARD ?= "evk_1"
TFA_UBOOT ?= "1"
TFA_BUILD_TARGET ?= "bl2 fip"
BL2_BOOT_TARGET ?= "spi mmc esd"
EXTRA_IMAGEDEPENDS += " firmware-pack"

BL2_BASE_ADDR ?= "0x08103000"
BL2_ADJUST_VMA ?= "0x08101E00"
FIP_ADJUST_VMA ?= "0x0"

# U-Boot Configuration
PREFERRED_VERSION_u-boot ?= "2024.07%"
UBOOT_CONFIG ??= "rzv2h-evk-ver1"
UBOOT_CONFIG[rzv2h-evk-ver1] = "rzv2h-evk-ver1_defconfig"

# flash writer
EXTRA_IMAGEDEPENDS += " flash-writer"

# firmware pack
EXTRA_IMAGEDEPENDS += " firmware-pack"

# Supported devicetree
KERNEL_DEVICETREE = " \
	renesas/r9a09g057h44-rzv2h-evk.dtb \
	renesas/r9a09g057h44-rzv2h-evk-cn15-sd.dtb \
	renesas/r9a09g057h44-rzv2h-evk-cn15-emmc.dtb \
"

IMAGE_BOOT_FILES = " \
	bl2_bp_spi-${MACHINE}.bin \
	bl2_bp_spi-${MACHINE}.srec \
	bl2_bp_mmc-${MACHINE}.bin \
	bl2_bp_mmc-${MACHINE}.srec \
	fip-${MACHINE}.bin \
	fip-${MACHINE}.srec \
	Flash_Writer_SCIF_RZV2H_DEV_INTERNAL_MEMORY.mot \
"

# Wic image
WKS_FILE = "rz-image-bootpart-esd.wks"
do_image_wic[depends] += "firmware-pack:do_deploy"
