#@TYPE: Machine
#@NAME: smarc-rzg3l
#@DESCRIPTION: Reference machine configuration for the RZ/G3L Smarc Board

require conf/machine/include/arm/armv8-2a/tune-cortexa55.inc
require conf/machine/include/rz-common.inc
require conf/machine/include/rzg3l-family.inc

# Machine configuration
MACHINE_FEATURES:append = " alsa ext2 pci serial usbgadget usbhost can"

# Trusted Firmware-A configuration
PREFERRED_VERSION_trusted-firmware-a ?= "2.10%"
TFA_PLATFORM ?= "g3l"
TFA_BOARD ?= "smarc"
TFA_UBOOT ?= "1"
TFA_BUILD_TARGET ?= "bl2 fip"
BL2_BOOT_TARGET ?= "spi mmc esd"
BL2_BASE_ADDR ?= "0x23000"
BL2_ADJUST_VMA ?= "0x21E00"
FIP_ADJUST_VMA ?= "0x0000"
EXTRA_IMAGEDEPENDS += " firmware-pack"

# U-Boot Configuration
UBOOT_CONFIG ??= "smarc-rzg3l"
UBOOT_CONFIG[smarc-rzg3l] = "smarc-rzg3l_defconfig"
PREFERRED_VERSION_u-boot ?= "2024.07%"

# Linux kernel configuration
KERNEL_IMAGETYPE ?= "Image"
KERNEL_DEVICETREE ?= "renesas/r9a08g046l48-smarc.dtb"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-renesas"

IMAGE_BOOT_FILES = " \
	bl2_bp_spi-${MACHINE}.bin \
	bl2_bp_spi-${MACHINE}.srec \
	bl2_bp_mmc-${MACHINE}.bin \
	bl2_bp_mmc-${MACHINE}.srec \
	bl2_bp_esd-${MACHINE}.bin \
	bl2_bp_esd-${MACHINE}.srec \
	fip-${MACHINE}.bin \
	fip-${MACHINE}.bin \
	fip-${MACHINE}.srec \
	Flash_Writer_SCIF_RZG3L_SMARC_LPDDR4.mot \
"
do_image_wic[depends] += "firmware-pack:do_deploy flash-writer:do_deploy"
